name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4   

    - name: Run OpenScad
      # https://hub.docker.com/r/openscad/openscad/tags
      run: |
        docker run --rm -v $(pwd):/openscad openscad/openscad:dev.2025-02-03 openscad -o starter.stl starter.scad
        docker run --rm -v $(pwd):/openscad openscad/openscad:dev.2025-02-03 openscad -o examples.3.stl examples.3.scad